Fix typo in error message for missing config file

diff --git a/rotate-tlsa b/rotate-tlsa
--- a/rotate-tlsa
+++ b/rotate-tlsa
@@ -81,7 +81,7 @@ $(cat "${vardir}/${previous}")"
 					fi
 				fi
 			else
-				echo "Missing config file: $conffile"a >&2
+				echo "Missing config file: $conffile" >&2
 			fi
 		done
 	fi
